[BUG] #680 holiday calculation & [BUG] #295 overtime calculation
tosccolors/vertical-professional-services pull request #17
Opened 2024-04-11 12:53 UTC by kumarinie

2024-04-11 13:39 UTC, hbrunn commented
you should really install pre-commit following the link I posted in the other PR, otherwise you have to fix its [complaints](https://github.com/tosccolors/vertical-professional-services/actions/runs/8647034320/job/23707617978?pr=17#step:7:1) manually

2024-04-11 13:46 UTC, hbrunn requested changes

2024-04-11 13:46 UTC, hbrunn commented on ps_landing_page/models/hr_employee_landing_page.py
> +                self.employee_id.allocation_used_display)
if you have to do math with those fields, just use [allocation_count](https://github.com/OCA/OCB/blob/14.0/addons/hr_holidays/models/hr_employee.py#L92) and [allocation_used_count](https://github.com/OCA/OCB/blob/14.0/addons/hr_holidays/models/hr_employee.py#L97) in the first place

2024-04-12 11:49 UTC, hbrunn approved these changes

2024-04-15 12:21 UTC, Stephanvandenberg commented
Tested and works

2024-04-15 12:21 UTC, merged